plugins:
  - stylelint-scss
extends:
  - stylelint-config-standard
  - stylelint-config-prettier
rules:
  at-rule-no-unknown: null
  scss/at-rule-no-unknown: true
  no-descending-specificity: null
  font-family-no-missing-generic-family-keyword:
    - true
    - ignoreFontFamilies:
        - Font Awesome 5 Free
